### PR TITLE
span tag made accessible

### PR DESCRIPTION
**Pull request by divyaprakash-Rx**

### CODE REVIEW

**Comment by divyaprakash-Rx** [comment]
@praveenscience I have made the span tag accessible. Please review and merge PR

**Comment by AnjaliSharma1234** [comment]
@divyaprakash-Rx congratulations on your first time contribution. It would be more helpful for you as well as the organization if you follow the contribution guidelines(https://github.com/CatsInTech/Rezume/blob/master/CONTRIBUTING.md) of the project by @praveenscience for opening a pull request. Do check it out!

**Comment by divyaprakash-Rx** [comment]
Sure

**Comment by divyaprakash-Rx** [comment]
@AnjaliSharma1234 I have read the guidlines and created new PR for the same. Please review that.

**Pull request closed without merging**
