### PR TITLE
Implemented the "About Us" page and Implemented "react-router-dom" for routing to different pages

### PR DESCRIPTION
**Pull request by mayonk-kumar-git**
Fixes: # 101

## Proposed changes

-Implemented the react-router-dom to route/navigate between different pages
-Added About Us Page
-Added on Click to "Rezume" logo to route to Home Screen (* but have not designed home screen)

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots
1 - Copy
4 - Copy
2 - Copy
3 - Copy
5 - Copy

### CODE REVIEW

**Review by praveenscience — CHANGES_REQUESTED** [review]
Okay this is a really great attempt, but now I am thinking of having a separate repo + landing page for about us. Extremely sorry and apologies Mayonk, I'll send you a nice gift for this, but we're not taking this forward.

We'll use [Rezume-Landing-Page](https://rezyume.co/) for the same with simple HTML & CSS.

**Comment by mayonk-kumar-git** [comment]
@praveenscience  Ahh!! feels a little heartbroken 😞 But it's fine, had a great learning experience. Looking forward to working on some other issue. 😃

**Comment by praveenscience** [comment]
@mayonk-kumar-git Right away talk to me on LinkedIn. Will send you something worth 45 US$ you won't regret. 🎉

**Comment by mayonk-kumar-git** [comment]
@praveenscience I am not sure how to message you over LinkedIn. It's asking for a premium account (and unfortunately I don't have one)
If you can message me (https://www.linkedin.com/in/mayonk-kumar/) then I might be able to reply.

**Comment by praveenscience** [comment]
@mayonk-kumar-git Add me as a connection man! 😁

**Pull request closed without merging**
