### PR TITLE
Footer added

### PR DESCRIPTION
**Pull request by n0noob**
## Issue that this pull request solves

Closes: #48 

## Proposed changes

Added footer

## Types of changes

_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

## Screenshots

Added footer
image

## Other information

Any other information that is important to this pull request

### CODE REVIEW

**Comment by praveenscience** [comment]
We've already looking into implementing #49, and it's simple too. You have got a lot of commented out stuff. Why?

**Comment by praveenscience** [comment]
Also, this was assigned to @aldrinjenson.

**Comment by aldrinjenson** [comment]
Yeah. @n0noob please check #49.

**Comment by n0noob** [comment]
@aldrinjenson it is all yours, **_deleted my branch_**.
@praveenscience the commented code was for it to be extended later.
Also, sorry, my bad I did not go through the whole conversation in #49 .

**Pull request closed without merging**
