### PR TITLE
Fixes#3

### LINKED ISSUE #3: Add CI / CD + Netlify Support
Currently we are using GitHub Pages and creating a build, pushing it to `gh-pages` branch and updating the build files by the following process in command line using :

- Delete the build folder.
- Recreate the build folder.
- Create a `CNAME` file.
- Using `gh-pages` package, deploy the contents of build to `gh-pages` branch.

The above process needs to be automated using Continuous Integration / Continuous Deployment Pipelines using either Travis-CI or GitHub Actions. Once the build is done, this needs to be deployed automatically, if everything is successful to `app.rezume.best` through Netlify. This is up for grabs! 😊

### PR DESCRIPTION
**Pull request by abhu-A-J**
fixes #3 
@praveenscience Sir, the production.yml will automatically deploy the merged content on master, automatically. 

For other settings that we talk about like preview links, I'll message you on slack since it requires another approach and not as per discussed one. You can review this and let me know if I need to change anything. 

Also, we should use the following features from netlify as discussed: 
- [GitHub pull request comments](https://docs.netlify.com/site-deploys/notifications/#github-pull-request-comments)
- [GIthub commit checks](https://docs.netlify.com/site-deploys/notifications/#github-commit-checks)
- [Github Commit Statuses](https://docs.netlify.com/site-deploys/notifications/#github-commit-statuses)

Thanks!

### CODE REVIEW

**Comment by praveenscience** [comment]
@abhu-A-J Let's review and finish this off today. 😁

**Comment by abhu-A-J** [comment]
> @abhu-A-J Let's review and finish this off today. 😁

Nice! Did you set up the cool stuff Sir? The docs which I had send?

**Comment by abhu-A-J** [comment]
@praveenscience Sir Any issues on this one?? It in review mode since long time.!? Are further discussions needed on this??

**Comment by praveenscience** [comment]
Hey bro, sorry got caught up with something else. I did check this out, and it's awesome. Let's have a call tomorrow to discuss about this and finish. 😊

**Comment by abhu-A-J** [comment]
> Hey bro, sorry got caught up with something else. I did check this out, and it's awesome. Let's have a call tomorrow to discuss about this and finish. 😊

Cool!!

**Comment by abhu-A-J** [comment]
@praveenscience Sir will this be merged within GSSoC period?

**Pull request merged**
