### PR TITLE
Fixed Navigation error Issue 10

### PR DESCRIPTION
**Pull request by dibakar95**
#10 Fixed App structure in App.js
Closes: #10 
Brief description of what is fixed or changed
- Changed only setAppState

_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update (Documentation content changed)
- [ ] Other (please describe): 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by dibakar95** [comment]
@praveenscience Please review.

**Comment by dibakar95** [comment]
@praveenscience Please give a look, and tell me if I need to further make any changes

**Comment by dibakar95** [comment]
Can I have a review Please? @praveenscience @vermakhushboo @priyadharshinir1894 @PrathibhaS

**Comment by praveenscience** [comment]
@dibakar95 Can you fix the conflicts please?

**Pull request merged**
